### DISCUSSION TITLE
upgrade v3.2310.0 to v3.2311.0

### DISCUSSION THREAD

**Discussion by ColdWaterLW** [actiontech/sqle#2182] [Upgrade]
## 不兼容的变更内容
相关issue：https://github.com/actiontech/dms/issues/74
旧版本的插件配置在安装目录下的database_driver_option.yaml文件内，新版本将插件配置移动到 “安装目录/etc/config.yaml”文件

## 版本升级方案
新版本的SQLE 有配置变更，旧的SQLE升级到新SQLE需要手动修改配置文件，修改方式:
1. 进入目录“SQLE安装目录/etc/”
2. 将config.yaml.rpmsave文件重命名为config.yaml
3. 编辑config.yaml，添加“ database_driver_options”配置项，将原插件内容填写到“database_driver_options”配置项
### 举例
旧版本的database_driver_option.yaml文件内容如下：
```
driver:
  -
    db_type: MySQL
    logo_path: "/static/logo/mysql.png"
    params:
```

config.yaml文件内容如下：
```
dms:  
   ......
  service:
    database:
      username: root
      password: 123    
   ......
```

#### 修改后的config.yaml文件内容如下：
```
dms:  
   ......
  service:
    database:
      username: root
      password: 123    
   ......
  database_driver_options:   
    - db_type: MySQL
      logo_path: "/logo/mysql.png"
      params:
```
