### DISCUSSION TITLE
upgrade v3.2311.0 to v3.2312.0

### DISCUSSION THREAD

**Discussion by ColdWaterLW** [actiontech/sqle#2191] [Upgrade]
## 不兼容的变更内容
新版本的SQLE做了非兼容性变更，旧的SQLE升级到新SQLE需要额外的手动升级操作。相关issue：
https://github.com/actiontech/dms/issues/120
https://github.com/actiontech/sqle-ee/issues/1229
https://github.com/actiontech/sqle-ee/issues/1272
https://github.com/actiontech/sqle/issues/2154

### 启动SQLE服务前
假设SQLE的元数据库名为"sqle"，升级rpm包后，启动SQLE服务前，在元数据实例执行如下SQL：
```
use sqle;
ALTER TABLE sql_manages DROP COLUMN endpoint;
ALTER TABLE audit_plan_sqls_v2 DROP COLUMN endpoint;

ALTER TABLE `black_list_audit_plan_sqls` DROP INDEX `filter_sql`;
ALTER TABLE `black_list_audit_plan_sqls` CHANGE `filter_sql` `filter_content` VARCHAR(512) NOT NULL;

SET GLOBAL FOREIGN_KEY_CHECKS=0;
```

修改配置文件，新增“auto_migrate”字段
```
dms:  
   ......
  service:
    database:
      username: root
      password: 123 
      auto_migrate: true      # 新增字段
   ......
```

### 启动SQLE服务后
启动SQLE服务后，在元数据实例执行如下SQL：
```
SET GLOBAL FOREIGN_KEY_CHECKS=1;
```
对于MySQL规则模板中启用了，索引优化标签下的 “索引创建建议” 的规则模板，需要手动编辑规则模板，将索引创建建议的 “列区分度最低值阈值（百分比）“ 修改为2
