### ISSUE TITLE
支持集群模式【企业版】

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1385]
## 架构
SQLE server 绝大部分业务是基于数据库的无状态web服务，对外提供接口。不同的SQLE 服务进程之间天生是共享数据的（连接同一个业务库）。
![image](https://user-images.githubusercontent.com/18008452/227845496-55130a69-bc8f-40ad-a0d5-40911ecb031e.png)
## 本期目标
1. 支持集群模式，支持主宕机后，从能够提升为主并支持后台任务（工单定时上线，智能扫描任务，工单回收，外部数据源对接，钉钉工单对接）保证任务能在主上进行执行
2. 工单定时上线确保一致性，不会被重复执行
3. 许可证支持集群模式，且兼容老的许可
## 使用
入口在 SQLE 的配置文件中，需要重启生效，影响参数如下表：
<div class="table-wrap" style="margin: 10px 0px 0px; padding: 0px; overflow-x: auto; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

参数 | 说明 | 备注
-- | -- | --
server:sqle_config:enable_cluster_mode | 是否开启集群模式 |  
server:sqle_config:server_id | SQLE节点的ID | 目前未对节点进行全局唯一校验，需要人工确认集群内不能重复，重复会导致出现多leader等情况

</div><br class="Apple-interchange-newline">

## 配置文件示例
注：同一个集群内的SQLE节点需连接同一个业务库（db_config）
```yml
  server:
    sqle_config:
      server_port: 10000
      auto_migrate_table: true
      debug_log: false
      log_path: './logs'
      plugin_path: './plugins'
      enable_cluster_mode: true #
      server_id: node_1 #
    db_config:
      mysql_cnf:
        mysql_host: 
        mysql_port: 
        mysql_user:
        mysql_password: 
        mysql_schema:
```
